FROM jenkins/jenkins:lts

USER root

RUN apt-get update -qq && \
    apt-get install -y -qq --no-install-recommends docker-cli kubectl && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN groupadd -g 973 docker && usermod -aG docker jenkins

COPY jenkins-entrypoint.sh /usr/local/bin/jenkins-entrypoint.sh
RUN chmod +x /usr/local/bin/jenkins-entrypoint.sh

USER jenkins
ENTRYPOINT ["/usr/local/bin/jenkins-entrypoint.sh"]
