sonar.projectKey=amine1919A_recruitment-ai-assistant
sonar.organization=amine1919a
sonar.sources=app,routes,database
sonar.exclusions=vendor/**,node_modules/**,public/**,resources/js/**,resources/css/**,*.js,*.ts,storage/**,bootstrap/**
sonar.host.url=https://sonarcloud.io
sonar.language=php
sonar.php.file.suffixes=.php